config/routes.rb
Rails.application.routes.draw do
  resources :colours

  resources :app_users, controller: 'users' do
    member do
      get :deactivate 
      get :activate
      get :update_password_activate
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions', 
  }

  
  resources :sizes
  resources :categories

  resources :products do 
    collection do 
      get :index_administration
    end
    member do 
      get :show_stock
      patch :modify_stock
      patch :soft_delete
    end
  end
  get 'product_category/:primary_category_id', to: 'products#index', as: 'filter_by_checkbox'
  get 'products/search', to: 'products#index', as: 'search_products'

  resource :cart, only: [:show] do
    post 'add_item', to: 'carts#add_item', as: 'add_item'
    delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
  end

  resources :cart_items, only: [:destroy, :update]

  resources :sales do 
    member do
      get :show_products
      post :cancel
    end
  end
  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable 

  validates :username, uniqueness: { message: "Este nombre de usuario ya está registrado"}
  validates :username, presence: true
  validates :phone_number, presence: { message: "El campo de número de teléfono no puede estar vacío" }
  validates :phone_number, format: { with: /\A\+\d{1,4}\d{1,10}\z/, message: "El número de teléfono no cumple con el formato" }, unless: -> { phone_number.blank? }
  has_one :cart, dependent: :destroy
  validates :username, format: { with: /\A[a-zA-Z\s]+\z/, message: "El nombre de usuario solo puede contener letras y espacios" }, if: -> { username.present? }

  def add_selected_roles(roles_from_form)
    if !roles_from_form.blank?
      roles_from_form.each do |role|
        self.add_role(role) if %w[admin manager employee].include?(role)
      end
    end
  end
  
  def delete_unselected_roles(roles_from_form)
    roles_actuales = self.roles

    if !roles_actuales.blank?
      if roles_from_form.blank?
        self.roles.each do |role|
          self.remove_role(role.name) 
        end
      else
        roles_actuales.each do |role|
          if !roles_from_form.include?(role.name)
            self.remove_role(role.name)
          end
        end
      end
    end
  end

  def deactivate_user()
    self.update_column(:status, 'inactive')
    self.password = SecureRandom.hex(10)
    self.save
  end

  def activate_user(new_password)
    self.password = new_password
    if self.valid?(:update_password) 
      self.update_column(:status, 'active')
      self.save
      return true
    else  
      return false
    end
  end



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  #permite que los usuarios autenticados accedan a las páginas de registro (xq ellos crean a los otros usuarios)
  skip_before_action :require_no_authentication, only: [:new, :create]


  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  #verifica si el usuario cuenta con los roles para crear otro usuario (debe tener admin o manager)
  before_action :authorize_role_assignment, only: [:new, :create]


  def new
    if current_user
      super
    else
      redirect_to root_path, alert: 'No cuentas con el rol para poder registrar usuarios.'
    end
  end

  def create
    build_resource(sign_up_params.except(:role))
    if resource.save
      assign_role(resource)
      flash[:notice] = 'Se ha creado el usuario.'
      redirect_to app_users_path and return
    else
      render :new
    end
  end
  
  protected

    def assign_role(user)
      if !params[:user][:role].blank?
        if current_user.has_role?(:admin)
          params[:user][:role].each do |role|
            user.add_role(role) if %w[admin manager employee].include?(role)
          end
        elsif current_user.has_role?(:manager)
          params[:user][:role].each do |role|
            user.add_role(role) if %w[manager employee].include?(role)
          end
        end
      end
    end

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :phone_number, :role])
    end
    
    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:username, :phone_number, :role])
    end
    
    def authorize_role_assignment
      unless !current_user || current_user.has_role?(:admin) || current_user.has_role?(:manager)
        redirect_to root_path, alert: 'No cuentas con el rol para poder crear usuarios'
      end
    end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy deactivate activate update_password_activate]
    helper_method :user_roles
    before_action :allowed_roles 
    before_action :authenticate_user! 


    def index  
      @users = User.all
    end
    
    def new  
      @user = User.new
    end

    def show
    end
    
    
    def edit
      if @user.status == 'inactive'
        redirect_to app_users_path, alert: "Debe activar el usuario primero"
      end 
    end

    def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          assign_role(@user)
          format.html { redirect_to app_users_path, notice: "El usuario fue creado exitosamente." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
    

    def update
      es_el_mismo = @user == current_user
      #si no se ingreso la pw para ser modificada, se actualizan los parametros sin el campo pw (en nil)
      if !user_params[:password].present?
        user_params_aux = user_params.except(:password) if user_params.present?
      else
        user_params_aux = user_params
      end
      if @user.update(user_params_aux)
        #agrega los roles que se seleccionaron
        @user.add_selected_roles(params[:user][:role])
        #itera entre los roles del usuario y elimina los que no fueron seleccionados
        @user.delete_unselected_roles(params[:user][:role])
        redirecciones_update(es_el_mismo)
      else  
        redirecciones_update_error_validacion()
      end
    end


    def destroy
      @user.destroy!
      respond_to do |format|
        format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def deactivate
      if current_user != @user && current_user.has_role?(:admin) && @user.status == 'active' 
        @user.deactivate_user()
        redirect_to app_users_path, notice: 'El usuario ha sido desactivado correctamente.'
      end
    end

    def activate
      if current_user != @user && current_user.has_role?(:admin) && @user.status != 'active' 
        if @user.activate_user(params[:user][:password])
          redirect_to app_users_path, notice: 'El usuario ha sido activado correctamente.' and return
        else
          render :update_password_activate_app_user
        end
      else
        flash[:alert] = 'Error al asignar la nueva contraseña'
        render :update_password_activate_app_user
      end
    end

    def update_password_activate
      if !(current_user != @user && current_user.has_role?(:admin) && @user.status != 'active')
        redirect_to app_users_path, alert: 'Este usuario ya está activo.'
      else  
        render :update_password_activate_app_user
      end
    end


    private
      def assign_role(user)
        if !params[:user][:role].blank?
          if current_user.has_role?(:admin)
            params[:user][:role].each do |role|
              user.add_role(role) if %w[admin manager employee].include?(role)
            end
          elsif current_user.has_role?(:manager)
            params[:user][:role].each do |role|
              user.add_role(role) if %w[manager employee].include?(role)
            end
          end
        end
      end

      def allowed_roles()
        if current_user && 
          !current_user.has_any_role?(:admin, :manager)
          redirect_to root_path
        end
      end

      def set_user
        @user = User.find(params.expect(:id))
      end

      def user_params
        params.expect(user: [ :name, :username, :email, :phone_number, :password, :role ])
      end

      def user_roles(user)
        return user.roles.pluck(:name).join(", ")
      end

      def redirecciones_update(es_el_mismo)
        respond_to do |format|
          if !es_el_mismo
            format.html { redirect_to app_users_path, notice: "El usuario fue actualizado correctamente." }
          else  
            format.html { redirect_to new_user_session_path, notice: "El usuario fue actualizado correctamente. Vuelve a iniciar sesión." }
          end
          format.json { render :show, status: :ok, location: @user }
        end
      end

      def redirecciones_update_error_validacion()
        respond_to do |format|

          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
end

app/views/users/_form.html.erb
<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Editar usuario</h3>
            <%= form_with(model: @user, url: app_user_path, method: :put) do |form| %>
              <% if @user.errors.any? %>
                <div>
                  <% @user.errors.each do |error| %>
                    <p class="alert alert-danger"><%= error.full_message %></p>
                  <% end %>
                </div>
              <% end %>

              <div class="form-outline mb-3">
                <%= form.label :username, "Nombre de usuario", class: "form-label" %>
                <%= form.text_field :username, class: "form-control form-control-sm", placeholder: "Nombre de usuario" %>
              </div>
              
              <div class="form-outline mb-3">
                <%= form.label :email, "Correo electrónico", class: "form-label" %>
                <%= form.email_field :email, class: "form-control form-control-sm" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :phone_number, "Teléfono", class: "form-label" %>
                <%= form.text_field :phone_number,:maxlength => 15, class: "form-control form-control-sm", placeholder: "Ejemplo: +542213456789" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :password, "Contraseña (opcional)", class: "form-label" %>
                <%= form.password_field :password, class: "form-control form-control-sm" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :role, "Rol", class: "form-label" %><br />
                <% roles = current_user.has_role?(:admin) ? ['admin', 'manager', 'employee'] : ['manager', 'employee'] %>
                <% roles.each do |role| %>
                  <div class="form-check">
                    <%= check_box_tag 'user[role][]', role, @user.has_role?(role), class: 'form-check-input', id: "#{role}Role" %>
                    <%= label_tag "#{role}Role", t("roles.#{role}"), class: 'form-check-label' %>
                  </div>
                <% end %>
              </div>
            

              <div class="mt-3 pt-2 d-flex justify-content-between">
                <%= link_to "Volver a usuarios", app_users_path, class: "btn btn-secondary btn-sm w-20" %>
                <%= form.submit "Confirmar cambios", class: "btn btn-primary btn-sm w-20" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Nombre de usuario:</strong>
    <%= user.username %>
  </p>
  <p>
    <strong>Correo electrónico:</strong>
    <%= user.email %>
  </p>
  <p>
    <strong>Número de teléfono:</strong>
    <%= user.phone_number %>
  </p>
  <p>
    <strong>Roles:</strong>
    <% user.roles.each  do |rol| %>
      <%= rol.name %>
    <% end %>
  </p>

</div>

app/views/users/edit.html.erb
<% content_for :title, "Editar usuario" %>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% if alert %>
<p class="alert alert-danger">
  <%= alert %>
</p>
<% end %>
<% content_for :title, "Usuarios" %>
  <div class="m-4">
    <div class="d-flex justify-content-between mb-4">
      <h2 class="mb-0">Panel de Usuarios</h2>
      <div class="d-flex">
        <%= link_to "Nuevo usuario", new_app_user_path, class: "btn btn-success" %>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nombre de usuario</th>
          <th scope="col">Correo</th>
          <th scope="col">Estado</th>
          <th scope="col">Roles</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <% if user.status == 'active' %>
              <td style="color: green">Activo</td>
            <% else %>
              <td style="color: red">Inactivo</td>
            <% end %>
            <td>  <%= user.roles.map { |role| I18n.t("roles.#{role.name}") }.join(', ') %> </td>
            <td>
              <% if (user.roles.pluck(:name).include? "admin") %>
                <% if current_user.has_role?(:admin) %>
                  <%= link_to "Editar usuario", edit_app_user_path(user), 
                  class: "btn btn-primary #{'disabled' unless user.status == 'active'}" %>
                <% end %>
              <% else %>
                <%= link_to "Editar usuario", edit_app_user_path(user), class: "btn btn-primary" %>
              <% end %>
              <% if current_user != user && current_user.has_role?(:admin) %>
                <% if user.status == 'active' %>
                  <%= link_to "Desactivar usuario", deactivate_app_user_path(user), method: :get, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to "Activar usuario", update_password_activate_app_user_path(user), method: :get, class: "btn btn-success" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>

  </div>

app/views/users/new.html.erb
<% content_for :title, "Nuevo usuario" %>

<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Registrar usuario</h3>
            <%= form_for(@user, url: app_users_path, method: :post) do |form| %>
              <% if @user.errors.any? %>
                <div>
                  <% @user.errors.each do |error| %>
                    <p class="alert alert-danger"><%= error.full_message %></p>
                  <% end %>
                </div>
              <% end %>

              <div class="form-outline mb-3">
                <%= form.label :username, "Nombre de usuario", class: "form-label" %>
                <%= form.text_field :username, class: "form-control form-control-sm" %>
              </div>
              
              <div class="form-outline mb-3">
                <%= form.label :email, "Correo electrónico", class: "form-label" %>
                <%= form.email_field :email, class: "form-control form-control-sm" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :phone_number, "Teléfono", class: "form-label" %>
                <%= form.text_field :phone_number,:maxlength => 15, class: "form-control form-control-sm", placeholder: "Ejemplo: +542213456789" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :password, "Contraseña (mínimo 6 caracteres)", class: "form-label" %>
                <%= form.password_field :password, class: "form-control form-control-sm" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :role, "Rol", class: "form-label" %><br />
                <% roles = current_user.has_role?(:admin) ? ['admin', 'manager', 'employee'] : ['manager', 'employee'] %>
                <% roles.each do |role| %>
                  <div class="form-check">
                    <%= check_box_tag 'user[role][]', role, @user.has_role?(role), class: 'form-check-input', id: "#{role}Role" %>
                    <%= label_tag "#{role}Role",  t("roles.#{role}"), class: 'form-check-label' %>
                  </div>
                <% end %>
            </div>
            

              <div class="mt-3 pt-2 d-flex justify-content-between">
                <%= link_to "Volver a usuarios", app_users_path, class: "btn btn-secondary btn-sm w-20" %>
                <%= form.submit "Confirmar", class: "btn btn-primary btn-sm w-20" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<%= render @user %>

<div>
  <%= link_to "Editar este usuario", edit_app_user_path(@user) %> |
  <%= link_to "Volver a usuarios", app_users_path %>

  <%= button_to "Eliminar usuario", app_user_path(@user), method: :delete %>
</div>

app/views/users/update_password_activate_app_user.html.erb
<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Asignar nueva contraseña a <%= @user.username %></h3>

            <%= form_for(@user, url: activate_app_user_path(@user), method: :get) do |f| %>
              <% if @user.errors.any? %>
                <div>
                  <% @user.errors.each do |error| %>
                    <p class="alert alert-danger"><%= error.full_message %></p>
                  <% end %>
                </div>
              <% end %>
              <div class="form-group">
                <%= f.label :password, "Nueva Contraseña" %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class="mt-3 pt-2 d-flex justify-content-between">
                <%= link_to "Volver a usuarios", app_users_path, class: "btn btn-secondary btn-md w-20" %>
                <%= f.submit "Activar Usuario", class: 'btn btn-primary' %>
              </div>
              
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>