config/routes.rb
Rails.application.routes.draw do
  resources :colours

  resources :app_users, controller: 'users' do
    member do
      get :deactivate 
      get :activate
      get :update_password_activate
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions', 
  }

  
  resources :sizes
  resources :categories

  resources :products do 
    collection do 
      get :index_administration
    end
    member do 
      get :show_stock
      patch :modify_stock
      patch :soft_delete
    end
  end
  get 'product_category/:primary_category_id', to: 'products#index', as: 'filter_by_checkbox'
  get 'products/search', to: 'products#index', as: 'search_products'

  resource :cart, only: [:show] do
    post 'add_item', to: 'carts#add_item', as: 'add_item'
    delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
  end

  resources :cart_items, only: [:destroy, :update]

  resources :sales do 
    member do
      get :show_products
      post :cancel
    end
  end
  root "home#index"
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product
    validates :category_name, presence: true
    validates :category_name, uniqueness: { message: "El nombre de la categoría no puede repetirse. Elige otro." }
    validates :parent_id, presence: { message: "Debe elegir una categoría principal."}
    belongs_to :parent, class_name: 'Category', optional: true
    has_many :subcategories, class_name: 'Category', foreign_key: 'parent_id'
    validates :category_name, format: { with: /\A[a-zA-Z\s]+\z/, message: "El nombre de la categoría solo puede contener letras y espacios" }, if: -> { category_name.present? }

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 

  # GET /categories or /categories.json
  def index
    @categories = Category.where.not(parent_id: nil)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "La categoría se creó correctamente." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "La categoría se actualizó correctamente." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :category_name, :parent_id])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Category name:</strong>
    <%= category.category_name %>
  </p>

</div>

app/views/categories/_form.html.erb
<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Editar categoría</h3>
            <%= form_for(@category, url: category_path, method: :put) do |form| %>
              <% if @category.errors.any? %>
                <div>
                  <% @category.errors.each do |error| %>
                    <p class="alert alert-danger"><%= error.full_message %></p>
                  <% end %>
                </div>
              <% end %>

              <div class="form-outline mb-3">
                <%= form.label :category_name, "Nombre", class: "form-label" %>
                <%= form.text_field :category_name, class: "form-control form-control-sm" %>
              </div>

              <div class="form-outline mb-3">
                <%= form.label :parent_id, "Categoría principal", class: "form-label" %>
                <%= form.select :parent_id, @primary_categories.map { |category| [category.category_name, category.id] }, { prompt: "Selecciona una categoría principal" }, class: "form-select" %>
              </div>
              <div class="mt-3 pt-2 d-flex justify-content-between">
                <%= link_to "Volver a las categorías", categories_path, class: "btn btn-secondary btn-sm w-20" %>
                <%= form.submit "Guardar", class: "btn btn-primary btn-sm w-20" %>
              </div>

            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/categories/edit.html.erb
<% content_for :title, "Editar categoría" %>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% if alert %>
<p class="alert alert-danger">
  <%= alert %>
</p>
<% end %>
<% content_for :title, "Categorías" %>
  <div class="m-4">
    <div class="d-flex justify-content-between mb-4">
      <h2 class="mb-0">Panel de Categorías</h2>
      <div class="d-flex gap-2">
        <%= link_to "Nueva categoría", new_category_path, class: "btn btn-success" %>
        <%= link_to "Volver a los productos", index_administration_products_path, class: "btn btn-secondary" %>

      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Nombre</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.category_name %></td>
            <td><%= link_to "Editar categoría", edit_category_path(category), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>

    </table>

  </div>

app/views/categories/new.html.erb
<% content_for :title, "Nueva categoría" %>

<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Crear categoría</h3>
              <%= form_for(@category, url: categories_path, method: :post) do |form| %>
                <% if @category.errors.any? %>
                  <div>
                    <% @category.errors.each do |error| %>
                      <p class="alert alert-danger"><%= error.full_message %></p>
                    <% end %>
                  </div>
                <% end %>

                <div class="form-outline mb-3">
                  <%= form.label :category_name, "Nombre", class: "form-label" %>
                  <%= form.text_field :category_name, class: "form-control form-control-sm" %>
                </div>
                <div class="form-outline mb-3">
                  <%= form.label :parent_id, "Categoría principal", class: "form-label" %>
                  <%= form.select :parent_id, @primary_categories.map { |category| [category.category_name, category.id] }, { prompt: "Selecciona una categoría principal" }, class: "form-select" %>
                </div>
                <div class="mt-3 pt-2 d-flex justify-content-between">
                  <%= link_to "Volver a las categorías", categories_path, class: "btn btn-secondary btn-sm w-20" %>
                  <%= form.submit "Guardar", class: "btn btn-primary btn-sm w-20" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/categories/show.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>