config/routes.rb
Rails.application.routes.draw do
  resources :colours

  resources :app_users, controller: 'users' do
    member do
      get :deactivate 
      get :activate
      get :update_password_activate
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions', 
  }

  
  resources :sizes
  resources :categories

  resources :products do 
    collection do 
      get :index_administration
    end
    member do 
      get :show_stock
      patch :modify_stock
      patch :soft_delete
    end
  end
  get 'product_category/:primary_category_id', to: 'products#index', as: 'filter_by_checkbox'
  get 'products/search', to: 'products#index', as: 'search_products'

  resource :cart, only: [:show] do
    post 'add_item', to: 'carts#add_item', as: 'add_item'
    delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
  end

  resources :cart_items, only: [:destroy, :update]

  resources :sales do 
    member do
      get :show_products
      post :cancel
    end
  end
  root "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  has_many :product_sizes
  has_many :sizes, through: :product_sizes
  belongs_to :category
  belongs_to :colour, optional: true  

  validates :images, presence: true, on: :create
  validates :name, presence: true
  validates :price, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}, if: -> { price.present? }
  validates :description, presence: true
  validates :stock, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true
  validate :image_limit


  def image_limit
    if images.length > 4
      errors.add(:images, "No puede haber más de 4 imágenes por producto.")
    end
  end

  def delete_product_sizes()
    ProductSize.where(product_id: self.id).delete_all
  end

  def update_or_create_product_sizes(product_sizes)
    return if product_sizes.blank?
    product_sizes.each do |size_data|
      if self.product_sizes.exists?(size_id: size_data[:size_id]) && size_data[:product_size_stock].blank?
        size_data[:product_size_stock] = 0
      end
      next if size_data[:product_size_stock].blank?
      if ProductSize.exists?(size_id: size_data[:size_id], product_id: self.id)
        product_size_edit = ProductSize.find_by(product_id: self.id, size_id: size_data[:size_id])
        if product_size_edit.product_size_stock != size_data[:product_size_stock].to_i
          ProductSize.where(product_id: self.id, size_id: size_data[:size_id]).update_all(product_size_stock: size_data[:product_size_stock].to_i)
        end
      else
        ProductSize.create!(
          product_id: self.id,
          size_id: size_data[:size_id],
          product_size_stock: size_data[:product_size_stock],
        )
      end
    end
  end

  def modify_global_stock(new_stock)
    if self.stock != new_stock
      self.update_column(:stock, new_stock)
    end
  end

  def modify_size_stock(sizes_data)
    #itero sobre los distintos talles con stock
    sizes_data.each do |size_data|
      product_size_edit = ProductSize.find_by(product_id: self.id, size_id: size_data[:size_id])
      #comparo el stock del talle quetengo guardado con el ingresado por parametro paraver si es nacesario actualizar
      if product_size_edit.product_size_stock != size_data[:product_size_stock].to_i
        product_size_edit.product_size_stock = size_data[:product_size_stock].to_i
        ProductSize.update_stock(self.id, size_data[:size_id], size_data[:product_size_stock].to_i)
      end
    end
  end


  def has_stock(quantity, size_id)
    if !size_id.blank? && self.product_sizes.any?
      product_size_selected = ProductSize.find_by(size_id: size_id, product_id: self.id)
      return product_size_selected.product_size_stock >= quantity
    else  
      return self.stock >= quantity
    end
  end

  def has_size_without_size_id_sent?(size_id)
    return self.product_sizes.any? ? size_id.blank? : false
  end

  def update_stock_global(stock)
    self.update_column(:stock, stock)
  end

  def update_size_stock(quantity, size_id)
    product_size_stock = ProductSize.find_by(size_id: size_id, product_id: self.id).product_size_stock
    ProductSize.update_stock(self.id, size_id, product_size_stock - quantity)
  end

  def self.search_filter(query)
    return where("name LIKE ? OR description LIKE ?", "%#{query}%", "%#{query}%")
  end
  
  def self.category_filter(subcategories_ids)
    return where(category_id: subcategories_ids)
  end
  
  def self.colour_filter(colours_id)
    return where(colour_id: colours_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy soft_delete show_stock modify_stock ]
  before_action :authenticate_user!, only: %i[ create edit update destroy index_administration ] 

  # GET /products or /products.json

  def index
    @products = Product.where(delete_date: nil)  
    if params[:query].present?
      @products = @products.search_filter(params[:query])
      render :index_search and return 

    else
      @category_selected = Category.find(params[:primary_category_id].to_i)
      @subcategories_ids = @category_selected.subcategories.pluck(:id)

      #filtro por subcategoría
      if params[:category].present?
        @products = @products.category_filter(params[:category])
      end

      if params[:color].present?
        @products = @products.colour_filter(params[:color])
      end
      
      if params[:primary_category_id].present?
        @products = @products.category_filter(@subcategories_ids)
      end
    end
  end


  def index_administration
    @products = Product.where(delete_date: nil) 
  end

  # GET /products/1 or /products/1.json
  def show
    if @product.delete_date
      redirect_to root_path
    end
  end

  # GET /products/new
  def new
    if current_user && current_user.has_any_role?(:admin, :manager, :employee)
      @product = Product.new
      @categories = Category.where.not(parent_id: nil)
      @colours = Colour.all
    else
      redirect_to root_path
    end
  end

  # GET /products/1/edit

  def edit
    if !@product.delete_date
      @categories = Category.where.not(parent_id: nil)
      @colours = Colour.all
    else  
      redirect_to root_path
    end
  end

  # POST /products or /products.json
  def create
    if current_user && current_user.has_any_role?(:admin, :manager, :employee)
      @product = Product.new(product_params.except(:product_sizes))
      @categories = Category.all
      @colours = Colour.all
      respond_to do |format|
        if @product.save
          if product_params[:stock].blank?
            @product.update_or_create_product_sizes(params[:product][:product_sizes])
          end
          format.html { redirect_to @product, notice: "El producto fue creado" }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @categories = Category.all
    respond_to do |format|
      if params[:product][:images] == [""]
        params[:product].delete(:images)
      end

      if @product.update(product_params)

        if product_params[:stock].blank?
          @product.update_or_create_product_sizes(params[:product][:product_sizes_attributes])
        else  
          if @product.product_sizes
            @product.delete_product_sizes()
          end
        end

        format.html { redirect_to @product, notice: "El producto se actualizó correctamente" }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


    
  def soft_delete 
    @product.delete_date = DateTime.now
    if @product.save
      if @product.product_sizes.any?
        ProductSize.stock_a_cero(@product.id)
      else
        @product.update_column(:stock, 0)
      end
      redirect_to index_administration_products_path, notice: "El producto fue eliminado correctamente"
    else
      redirect_to index_administration_products_path, alert: "Hubo un error al intentar eliminar el producto"
    end
  end




  # DELETE /products/1 or /products/1.json
  def destroy
    if current_user && current_user.has_any_role?(:admin, :manager, :employee)
      @product.destroy!

      respond_to do |format|
        format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    else  
      redirect_to root_path
    end
  end

  def show_stock
    if @product.delete_date
      redirect_to root_path
    end
  end

  def modify_stock
    
    if @product.product_sizes.any?
      @product.modify_size_stock(params[:product][:product_sizes_attributes])
    else
      @product.modify_global_stock(params[:product][:stock].blank? ? 0 : params[:product][:stock].to_i)
    end
  
    redirect_to index_administration_products_path, notice: 'El stock se actualizó correctamente.'
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.expect(product: [ :name, :description, :price, :stock, :colour_id, :category_id, images: [], product_sizes: [:size_id, :product_size_stock ] ])
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Editar producto</h3>
            <div data-controller="product-create">
              <%= form_for(@product, url: product_path, method: :put) do |form| %>
                <% if @product.errors.any? %>
                  <div>
                    <% @product.errors.each do |error| %>
                      <p class="alert alert-danger"><%= error.full_message %></p>
                    <% end %>
                  </div>
                <% end %>
              
                <div class="form-outline mb-3">
                  <%= form.label :name, "Nombre", class: "form-label" %>
                  <%= form.text_field :name, class: "form-control form-control-sm" %>
                </div>
                
                <div class="form-outline mb-3">
                  <%= form.label :description, "Descripción", class: "form-label" %>
                  <%= form.text_field :description, class: "form-control form-control-sm" %>
                </div>
              
                <div class="form-outline mb-3">
                  <%= form.label :price, "Precio", class: "form-label" %>
                  <%= form.text_field :price, class: "form-control form-control-sm" %>
                </div>
                
                <div class="form-outline mb-3">
                  <%= form.label :stock, "Stock (dejar vacío si el producto tiene talles)", class: "form-label" %>
                  <%= form.number_field :stock, min: 0, class: "form-control form-control-sm", data: { product_create_target: "stock", action: "input->product-create#updateStock" } %>
                </div>
              
                <div data-product-create-target="sizesContainer">
                  <h5 class="mt-4 mb-3">Stock por talles</h5>
                  <% @product.product_sizes.each do |product_size| %>
                    <div class="form-group mb-3">
                      <%= fields_for "product[product_sizes_attributes][]", product_size do |ps| %>
                        <%= ps.hidden_field :size_id, value: product_size.size_id %>
                        <%= ps.label :product_size_stock, "Talle #{product_size.size.size_value}", class: "form-label" %>
                        <%= ps.number_field :product_size_stock, min: 0, class: "form-control form-control-sm", placeholder: "Ingrese el stock", value: product_size.product_size_stock, data: { product_create_target: "sizeStock", action: "keydown->product-create#preventNegativeSignOnKeydown" } %>
                      <% end %>
                    </div>
                  <% end %>
              
                  <% Size.all.each do |size| %>
                    <% unless @product.product_sizes.exists?(size_id: size.id) %>
                      <div class="form-group mb-3">
                        <%= fields_for "product[product_sizes_attributes][]", ProductSize.new(size_id: size.id) do |ps| %>
                          <%= ps.hidden_field :size_id, value: size.id %>
                          <%= ps.label :product_size_stock, "Talle #{size.size_value}", class: "form-label" %>
                          <%= ps.number_field :product_size_stock, min: 0, class: "form-control form-control-sm", placeholder: "Ingrese el stock", data: { product_create_target: "sizeStock", action: "keydown->product-create#preventNegativeSignOnKeydown" } %>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                </div>

                <div class="form-outline mb-3">
                  <%= form.label :colour_id, "Color", class: "form-label" %>
                  <%= form.select :colour_id, @colours.map { |colour| [colour.name, colour.id] }, { prompt: "Selecciona un color" }, class: "form-select" %>
                </div>
              
                <div class="form-outline mb-3">
                  <%= form.label :category_id, "Categoría", class: "form-label" %>
                  <%= form.select :category_id, @categories.map { |category| [category.category_name, category.id] }, { prompt: "Selecciona una categoría" }, class: "form-select" %>
                </div>
              
                <div class="form-group mb-3">
                  <%= form.label :images, "Subir imagen", class: "form-label" %>
                  <%= form.file_field :images, multiple: true, accept: "image/*", class: "form-control" %>
                </div>
              
                <div class="mt-3 pt-2 d-flex justify-content-between">
                  <%= link_to "Volver a los productos", index_administration_products_path, class: "btn btn-secondary btn-sm w-20" %>
                  <%= form.submit "Guardar", class: "btn btn-primary btn-sm w-20" %>
                </div>
              <% end %>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/products/_product.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb" style="margin-left: 80px">
    <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>

    <% if current_user && current_user.has_any_role?(:admin, :manager, :employee)%>
      <li class="breadcrumb-item"><%= link_to "Productos", index_administration_products_path %></li>
    <% else %>
      <li class="breadcrumb-item"><%= link_to product.category.parent&.category_name || "Productos", filter_by_checkbox_path(primary_category_id: product.category.parent_id) %></li>
    <% end %>
    <li class="breadcrumb-item active" aria-current="page"><%= product.name %></li>
  </ol>
</nav>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<div class="container mb-3">
  <div class="row d-flex flex-row">
    <div class="col-md-4">
      <% if product.images.attached? %>
        <%= image_tag product.images.first, class: "producto-show-imagen", alt: product.name %>
      <% end %>
    </div>

    <div class="col-md-2 d-flex flex-column order-md-first">
      <% if product.images.attached? %>
        <% if product.images.length > 1 %>
          <% product.images.drop(1).each do |imagen| %>
            <div class="mb-2">
              <%= image_tag imagen, class: "producto-secundario-show-imagen", alt: product.name %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-5">
      <h1><%= product.name %></h1>
      <h5><%= product.description %></h5>
      <p class="display-4 text-success"><%= number_to_currency(product.price, precision: 0) %></p>
      
      <% if product.colour %>
        <p><strong>Color:</strong> <%= product.colour.name %></p>
      <% end %>  
      <% if product.product_sizes.any? %>
        <h5>Talles</h5>
        <div class="row">
          <% product.product_sizes.each do |product_size| %>
            <div class="col-6 col-sm-4 col-md-3 mb-2">
              <div class="card p-3 border rounded-3 position-relative">
                <div class="size-name text-center">
                  <%= Size.find(product_size.size_id).size_value.upcase %>
                </div>
                <div class="stock-info d-none text-center position-absolute top-0 start-0 w-100 h-100 bg-white opacity-80 d-flex justify-content-center align-items-center">
                  <p style="color: <%= product_size.product_size_stock > 0 ? 'green' : 'red' %>">
                    <%= product_size.product_size_stock %>
                  </p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <p><strong>Stock:</strong> <%= product.stock || 'No disponible' %></p>
      <% end %>
              
        <% if !(@product.stock.blank? && !@product.product_sizes.any?) %>
          <%= form_with url: add_item_cart_path, method: :post, local: true do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>

            <% if product.product_sizes.any? %>
              <div class="form-group">
                <%= f.label :size, "Seleccionar talle", class: "form-label" %>
                <%= f.select :size_id, product.product_sizes.map { |ps| 
                  if ps.product_size_stock > 0
                    size = Size.find(ps.size_id)
                    ["#{size.size_value.upcase} - stock: #{ps.product_size_stock}", ps.size_id]
                  end 
                  
                }.compact, prompt: "Elige un talle", class: "form-select" %>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :quantity, "Cantidad",  class: "form-label" %>
              <%= f.select :quantity, [1, 2, 3, 4, 5], class: "form-select" %>
            </div>

            <%= f.submit "Añadir al carrito", class: "btn btn-primary mt-3" %>
          <% end %>
        <% end %>

    </div>
  </div>
</div>

app/views/products/edit.html.erb
<% content_for :title, "Editar producto" %>


<%= render "form", product: @product %>

app/views/products/index.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% content_for :title, "Productos" %>

<div class="container mt-2">
  <div class="row align-items-start">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
          <li class="breadcrumb-item active" aria-current="page"><%= @category_selected.category_name%></li>
        </ol>
      </nav>
    </div>
    <div class="col-12">
      <h3 class="d-inline-block mb-4"><%= @category_selected.category_name%></h3>
    </div>
    <div class="col-md-3 mb-4">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Filtros</h5>
          <%= form_with(url: filter_by_checkbox_path, method: :get) do |form| %>
            <div class="mb-3">
              <%= form.label :category, "Categorías", class: "form-label" %>
              <% Category.where(id: @subcategories_ids).each do |sub_category| %>
                <div class="form-check">
                  <%= check_box_tag 'category[]', sub_category.id, params[:category]&.include?(sub_category.id.to_s), class: 'form-check-input', id: "#{sub_category.category_name}Category" %>
                  <%= label_tag "#{sub_category.category_name}Category", sub_category.category_name, class: 'form-check-label' %>
                </div>
              <% end %>
            </div>
            <div class="mb-3">
              <%= form.label :colour, "Colores", class: "form-label" %>
              <% Colour.all.each do |colour| %>
                <div class="form-check">
                  <%= check_box_tag 'color[]', colour.id, params[:color]&.include?(colour.id.to_s), class: 'form-check-input', id: "#{colour.name}Color" %>
                  <%= label_tag "#{colour.name}Color", colour.name, class: 'form-check-label' %>
                </div>
              <% end %>
            </div>
            <div class="mt-3 pt-1 d-flex justify-content-between">
              <%= button_tag(type: 'reset', class: 'btn btn-secondary btn-sm w-20 me-2', onclick: 'window.location.href = window.location.pathname;') do %>
                Restablecer filtros
              <% end %>  
              <%= form.submit "Aplicar filtros", class: "btn btn-primary btn-sm w-20" %>
            </div>
          <% end %>
          
        </div>
      </div>
    </div>

    <div class="col-md-9">
      <% if !@products.blank? %>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-md-4 mb-4" id="<%= dom_id product %>">
              <a href="<%= product_path(product) %>" class="card-link" style="text-decoration: none;">
                <div class="card shadow-sm h-100">
                  <div class="image-container overflow-hidden">
                    <% if product.images.attached? %>
                      <%= image_tag product.images.first, class: "card-img-top img-fluid producto-imagen", alt: product.name %>
                    <% else %>
                      <div class="d-flex justify-content-center align-items-center" style="height: 200px; background-color: #f0f0f0;">
                        <p class="text-muted">No imagen</p>
                      </div>
                    <% end %>
                  </div>
                  <hr class="my-1" style="border: 0.5px solid black;">
                  <div class="card-body d-flex flex-column" style="background-color: beige">
                    <h5 class="card-title text-truncate"><%= product.name %></h5>
                    <p class="card-text text-muted text-truncate" style="font-size: 0.9rem;">
                      <strong>Precio:</strong> $<%= product.price %><br>
                    </p>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>No hay productos que cumplan con los filtros seleccionados</p>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index_administration.html.erb
<% content_for :title, "Productos" %>
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<div class="m-4">
  <div class="d-flex justify-content-between mb-4">
    <h2 class="mb-0">Panel de Productos</h2>
    <div class="d-flex gap-2">
      <%= link_to "Nuevo producto", new_product_path, class: "btn btn-success" %>
        <button class="btn btn-primary dropdown-toggle" type="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
          Relacionado al producto
        </button>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=<%= categories_path %>>Categorías</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href=<%= sizes_path %>>Talles</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href=<%= colours_path %>>Colores</a>
      </div>
    </div>
  </div>
  <% if !@products.blank? %>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nombre del producto</th>
          <th scope="col">Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td class="d-flex gap-2">
              <%= link_to "Editar producto", edit_product_path(product), class: "btn btn-primary" %>
              <%= link_to "Modificar stock", show_stock_product_path(product), method: :get, class: "btn btn-warning" %>
              <%= button_to "Eliminar Producto", soft_delete_product_path(product), method: :patch, class: "btn btn-danger" %>
              <%= link_to "Ver producto", product_path(product), class: "btn btn-info" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    No hay productos
  <% end %>

</div>

app/views/products/index_search.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% content_for :title, "Productos" %>

<div class="container mt-2">
  <div class="row align-items-start">
    <div class="col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
          <li class="breadcrumb-item active" aria-current="page">Productos</li>
        </ol>
      </nav>
    </div>
    <div class="col-12">
      <h3 class="d-inline-block mb-4">Productos</h3>
    </div>
    <div class="col-12">
      <p>Se muestran resultados de "<%= params[:query] %>" </p>
    </div>

    <div class="col-md-9">
      <% if !@products.blank? %>
        <div class="row">
          <% @products.each do |product| %>
            <div class="col-md-4 mb-4" id="<%= dom_id product %>">
              <a href="<%= product_path(product) %>" class="card-link" style="text-decoration: none;">
                <div class="card shadow-sm h-100">
                  <div class="image-container overflow-hidden">
                    <% if product.images.attached? %>
                      <%= image_tag product.images.first, class: "card-img-top img-fluid producto-imagen", alt: product.name %>
                    <% else %>
                      <div class="d-flex justify-content-center align-items-center" style="height: 200px; background-color: #f0f0f0;">
                        <p class="text-muted">No imagen</p>
                      </div>
                    <% end %>
                  </div>
                  <hr class="my-1" style="border: 0.5px solid black;">
                  <div class="card-body d-flex flex-column" style="background-color: beige">
                    <h5 class="card-title text-truncate"><%= product.name %></h5>
                    <p class="card-text text-muted text-truncate" style="font-size: 0.9rem;">
                      <strong>Precio:</strong> $<%= product.price %><br>
                    </p>
                  </div>
                </div>
              </a>
            </div>
          <% end %>
        </div>
      <% else %>
        <p>No hay productos</p>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<%= render @product %>

app/views/products/show_stock.html.erb
<% content_for :title, "Modificar stock" %>

<section class="gradient-custom">
  <div class="container py-5 h-100">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
          <div class="card-body p-3 p-md-4">
            <h3 class="mb-4 pb-2 pb-md-0 mb-md-4">Modificar stock de <%= @product.name %></h3>

            <%= form_for(@product, url: modify_stock_product_path, method: :patch, data: { controller: "input" }) do |form| %>
              <% if @product.errors.any? %>
                <div>
                  <% @product.errors.each do |error| %>
                    <p class="alert alert-danger"><%= error.full_message %></p>
                  <% end %>
                </div>
              <% end %>

              <% if @product.stock.blank? && !@product.product_sizes.any? %>
                <p>El producto no tiene ningún tipo de stock asociado.</p>
                <%= link_to "Volver a los productos", index_administration_products_path, class: "btn btn-secondary btn-sm w-20" %>
              <% else %>      
                <% if @product.product_sizes.any? %>
                  <h5 class="mt-4 mb-3">Stock por talles</h5>
                  <% @product.product_sizes.each do |product_size| %>
                    <div class="form-group mb-3">
                      <%= fields_for "product[product_sizes_attributes][]", product_size do |ps| %>
                        <%= ps.hidden_field :size_id, value: product_size.size_id %>
                        <%= ps.label :product_size_stock, "Talle #{product_size.size.size_value}", class: "form-label" %>
                        <%= ps.number_field :product_size_stock, min: 0, class: "form-control form-control-sm", placeholder: "Ingrese el stock", value: product_size.product_size_stock, data: { input_target: "input" } %>
                      <% end %>
                    </div>
                  <% end %>
                <% else %>
                  <div class="form-outline mb-3">
                    <%= form.label :stock, "Stock", class: "form-label" %>
                    <%= form.number_field :stock, min: 0, class: "form-control form-control-sm", data: { input_target: "input" } %>
                  </div>
                <% end %>

                <div class="mt-3 pt-2 d-flex justify-content-between">
                  <%= link_to "Volver a los productos", index_administration_products_path, class: "btn btn-secondary btn-sm w-20" %>
                  <%= form.submit "Guardar", class: "btn btn-primary btn-sm w-20" %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>