config/routes.rb
Rails.application.routes.draw do
  resources :colours

  resources :app_users, controller: 'users' do
    member do
      get :deactivate 
      get :activate
      get :update_password_activate
    end
  end

  devise_scope :user do
    get 'users/sign_out' => "devise/sessions#destroy"
  end
  devise_for :users, only: [:sessions], controllers: {
    sessions: 'users/sessions', 
  }

  
  resources :sizes
  resources :categories

  resources :products do 
    collection do 
      get :index_administration
    end
    member do 
      get :show_stock
      patch :modify_stock
      patch :soft_delete
    end
  end
  get 'product_category/:primary_category_id', to: 'products#index', as: 'filter_by_checkbox'
  get 'products/search', to: 'products#index', as: 'search_products'

  resource :cart, only: [:show] do
    post 'add_item', to: 'carts#add_item', as: 'add_item'
    delete 'clear_cart', to: 'carts#clear_cart', as: 'clear_cart'
  end

  resources :cart_items, only: [:destroy, :update]

  resources :sales do 
    member do
      get :show_products
      post :cancel
    end
  end
  root "home#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
    <div class="container-fluid">
        <a class="navbar-brand color-letra fs-4 fw-bold" href="<%= root_path %>">
            Avivas
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <% @primary_categories.each do |primary_category| %>
                    <li class="nav-item">
                    <a class="nav-link color-letra fs-5 fw-medium" href="<%= filter_by_checkbox_path(primary_category.id) %>">
                        <%= primary_category.category_name %>
                    </a>
                    </li>
                <% end %>
                <!-- <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Otros
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Deportes</a>
                    </div>
                </li> -->
            </ul>
        </div>

        <div class="d-flex align-items-center ms-3">
            <%= form_with url: products_path, method: :get, class: 'd-flex' do %>    
                <div class="input-group">
                    <%= text_field_tag :query, params[:query], class: 'form-control shadow-sm', placeholder: 'Buscar productos', type: 'search', aria: { label: 'Search' } %>
                    <%= submit_tag 'Buscar', class: 'btn btn-outline-success shadow-sm' %>
                </div>
            <% end %>

            <% if current_user %>
                <div class="nav-item dropdown d-flex align-items-center ms-3">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= image_tag('iniciarsesion.png', alt: 'Avatar', class: 'rounded-circle', width: '40', height: '40') %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <div class="dropdown-item text-primary disabled" style="font-weight: bold;">
                            Hola, <%= current_user.username %>
                        </div>
                        <div class="dropdown-divider"></div>

                        <a class="dropdown-item" href="<%= sales_path %>">Ventas</a>
                        <a class="dropdown-item" href="<%= index_administration_products_path %>">Productos</a>
                        <% if current_user.has_any_role?(:admin, :manager) %> 
                            <a class="dropdown-item" href="<%= app_users_path %>">Usuarios</a>
                        <% end %>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<%= destroy_user_session_path %>" role="button">Cerrar sesión</a>
                    </div>
                </div>
            <% else %>
                <a class="btn btn-primary ms-3 shadow-sm" href="<%= new_user_session_path %>" role="button">Iniciar sesión</a>
                <%= link_to cart_path, class: 'ms-3' do %>
                        <%= image_tag('carrito.png', alt: 'Carrito', width: '30', height: '30') %>
                <% end %>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "TFI Ruby2024" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Página web de gestión de inventario de indumentaria deportiva">
    <meta name="author" content="Tomás Ilid">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

   
  </head>

  <body>
  <div class="estructura-divida">
   
      <header>
        <%=render "layouts/navbar"%>
      </header>

      <main style="background-color: #E4E4E4">
        <%= yield %>
      </main>

      <footer class="footer navbar navbar-expand-lg navbar-light bg-light shadow-sm py-3 mt-auto">
        <div class="container-fluid d-flex align-items-center justify-content-center">
          <p class="mb-0 color-letra fs-6">Tomás Ilid - TTPS Ruby 2024</p>
        </div>
      </footer>
  
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  
</html>